bug 1247: for pc2report change/update classpath
To fix: NoClassDefFoundError 
The Reports class (reports) now uses JSON and requires including
of all libraries under lib