i529: fixed --console, an earlier push broke it.
Added CONSOLE_OPTION_STRING  into allOptionStrings array.
That array was created after PR for 529 was created/PR pushed.  Since
CONSOLE_OPTION_STRING was not in the option list, using
CONSOLE_OPTION_STRING aka --console would fail with an
java.lang.IllegalArgumentException: invalid option '--console'
	at edu.csus.ecs.pc2.core.ParseArguments.loadArgs(ParseArguments.java:352)